### ISSUE TITLE
scrollView调用，会一直显示在背后

### ISSUE THREAD

**Issue by CCBrother** [dev-liyang/LYEmptyView#1]
_scrollView.ly_emptyView =  [LYEmptyView emptyActionViewWithImageStr:@"net"
                                                               titleStr:@"无数据"                                                            detailStr:@"查看网络设置，稍后再试!"
                                                             btnTitleStr:@"重新加载"
                                                                target:self
有数据的时候，也是显示在背后！

**Comment by yangli-dev** [comment]
scrollView是没有DataSource的，代码无法判断scrollView上有无数据，所以scrollView想要实现占位图，只能通过调用下面两个方法来手动控制emptyView的显示和隐藏。
/**
 手动调用显示emptyView
 */
- (void)ly_showEmptyView;
/**
 手动调用隐藏emptyView
 */
 - (void)ly_hideEmptyView;

**Comment by CCBrother** [comment]
原来如此，多谢了~

**Comment by yangli-dev** [comment]
不客气，是readme里没有注明，让大家产生歧义了，稍后我会更新readme文档

**Comment by CCBrother** [comment]
好的，多谢，到时我再查阅下~
