### ISSUE TITLE
tableView不会自动显示隐藏

### ISSUE THREAD

**Issue by SunnyYoung0917** [dev-liyang/LYEmptyView#11]
貌似和MJRefresh冲突了，导致添加占位视图刷新数据时mj_reloadData和ly_reloadData都没执行

**Comment by dev-liyang** [comment]
https://github.com/dev-liyang/LYEmptyView/blob/master/images/method_swizzling.png
请看图解，不管交换多少次都是不会冲突的。
如添加本框架就出现此问题，还烦请提供更详细的issue，来帮助我查找问题
