### ISSUE TITLE
iOS10崩溃了

### ISSUE THREAD

**Issue by qingshanbugai** [dev-liyang/LYEmptyView#15]
调用如下：

![image](https://user-images.githubusercontent.com/7610726/40594152-ecd87744-625f-11e8-8b77-4b2f53468652.png)

**Comment by qingshanbugai** [comment]
改好了，打扰了

**Comment by XiaBaKe** [comment]
我也遇到这个问题,请问楼上是怎么解决的

**Comment by qingshanbugai** [comment]
![](https://user-images.githubusercontent.com/7610726/41264875-b575beec-6e21-11e8-864b-d3c96aadd320.png)
这个问题暂时不知道原因，解决办法就是不要把设置代理的代码放在紧跟着初始化UITableView的后面，比如这里，27和28两行如果放在第20行就会崩溃。如果你是用xib直接设置代理，改成用代码设置就好了！

**Comment by qingshanbugai** [comment]
经过小伙伴测试，如果设置了tableView.tableFooterView = UIView()才会这样，没有设置就没事，很神奇！
