### ISSUE TITLE
建议：作者能扩展webview也支持这个框架吗？

### ISSUE THREAD

**Issue by Z-figaro** [dev-liyang/LYEmptyView#19]
如题，wkwebview也有加载进度的支持了，如果能支持；我觉得框架会更强大。我现在在扩展你的框架，如果我能写好，给你pull可以不？

**Comment by dev-liyang** [comment]
首先感谢你的建议。
在1.1.0版本前是支持scrollView的，webView.scrollView，所有是间接的支持webView。
但是在1.1.0版本开始，框架支持所有的view，所以是直接支持webView的
