### ISSUE TITLE
ios 10和ios9 下, 用自定义调用会卡死线程

### ISSUE THREAD

**Issue by GentleForYou** [dev-liyang/LYEmptyView#2]
我自定义的MyDIYEmpty继承于 LYEmptyView, 然后 MyDIYEmpty  调用emptyViewWithCustomView方法封装,  ios11正常, ios9和ios10 会卡死.  项目比较近,没时间研究是哪里的问题, 我就自己判断展位页面显示和隐藏.

**Comment by yangli-dev** [comment]
经测试，iOS10下没有卡死，甚至在iOS8下也能正常使用。
有一点请注意下，调用一次LYEmptyView中的构造方法就会alloc一个新的emptyView，造成资源浪费，如没特殊要求，可使用单例模式进行封装，保证不会一直创建

**Comment by GentleForYou** [comment]
具体的我也不太清楚,打断点进去看的时候好像是方法循环调用,一直循环,即便是真的是资源浪费,只要不是无限循环问题,也不至于直接卡死主线程,还是模拟器.模拟器内存限制很大的,不像真机限制120M .  我用模拟器测试和ios11的真机测试过,ios11 没问题,  ios9和ios10模拟器会卡死. 我们公司有一个ios10的真机,日版的,是测试发现的这个问题,后来我用模拟器实验,发现是ios9和ios10下,会卡死,ios11正常.  
由于没有国行ios9和ios10真机,所以也可能是xcode9下模拟器的问题.当时项目时间比较紧,没有仔细研究,后来我自己写的tableview分类加了一个方法,解决了项目问题. 回头我再看看,能不能找到原先的代码,提供给你

**Comment by ShenYj** [comment]
上周开始接触这个控件, 准备自定义一个contentview, 遇到过类似情况, cpu100%后挂掉,当时有问题就放弃了自定义customView
