### ISSUE TITLE
cocopod1.4.0搜不到

### ISSUE THREAD

**Issue by sysbol** [dev-liyang/LYEmptyView#3]
你好我这为啥搜不到？
Mac:~ gxz$ pod --version
1.4.0

Mac:~ $ pod search LYEmptyView
[!] Unable to find a pod with name, author, summary, or description matching `LYEmptyView`

**Comment by MR-THT** [comment]
192:hllm MR_THT$ pod --version
1.3.1
Mac:~ $ pod search LYEmptyView
[!] Unable to find a pod with name, author, summary, or description matching LYEmptyView

**Comment by yangli-dev** [comment]
提供几个参考的解决办法:
1.更新下本地仓库 $ pod repo update
2. 
   1) 执行命令重装 ，$ sudo gem install -n /usr/local/bin cocoapods   
   2) $ pod setup
3. 以上两种方式还不行，请参考 https://www.jianshu.com/p/9e4e36ba8574

**Comment by fishyumiao** [comment]
pod update 一下再搜就可以搜到了

**Comment by sysbol** [comment]
我的问题解决了，方法如下：
删除~/Library/Caches/CocoaPods目录下的search_index.json缓存文件
终端输入rm ~/Library/Caches/CocoaPods/search_index.json
删除成功后再执行pod search
会出现如下：
Creating search index for spec repo 'master'.. Done!，等待时间可能有点长，我的得二十多分钟吧。
出现Done后就可以。
