### ISSUE TITLE
CUICatalog: Invalid asset name supplied: (null)

### ISSUE THREAD

**Issue by EarthMass** [dev-liyang/LYEmptyView#30]
CUICatalog: Invalid asset name supplied: (null)
自定空页面 报错
 UIView * contentView = [[UIView alloc] init];
    contentView.frame = CGRectMake(0, 0, 100, 100);
    contentView.backgroundColor = [UIColor redColor];
    
没加子视图没问题，添加子视图报错
//    UILabel * titleLab = [[UILabel alloc] init];
//    titleLab.text = titleStr;
//    titleLab.font = FONT_MAIN;
//    titleLab.textColor = COLORF_MAIN;
//    [contentView addSubview:titleLab];
//    [titleLab mas_makeConstraints:^(MASConstraintMaker *make) {
//        (void)make.centerX.centerY;
//    }];
//
//    UILabel * desLab = [[UILabel alloc] init];
//    desLab.text = detailStr;
//    desLab.font = FONT_MAIN;
//    desLab.textColor = COLORF_MAIN;
//    [contentView addSubview:desLab];
//    [desLab mas_makeConstraints:^(MASConstraintMaker *make) {
//        (void)make.centerX;
//        make.top.mas_equalTo(titleLab.mas_bottom);
//    }];
    
    inView.ly_emptyView = [LYEmptyView emptyViewWithCustomView:contentView];

**Comment by dev-liyang** [comment]
是的，不支持autoLayout布局
