### ISSUE TITLE
UICollectionView (LJEmptyView)  insertItemsAtIndexPaths crash  交换的方法会引起crash，目前是IOS 10.1

### ISSUE THREAD

**Issue by guiqulaixi007** [dev-liyang/LYEmptyView#31]
0 | CoreFoundation | __exceptionPreprocess
-- | -- | --
1 | libobjc.A.dylib | objc_exception_throw
2 | CoreFoundation | +[NSException raise:format:]
3 | Foundation | -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4 | UIKit | -[UICollectionViewData indexPathForItemAtGlobalIndex:]
5 | UIKit | -[UICollectionViewData layoutAttributesForGlobalItemIndex:]
6 | UIKit | -[UICollectionView _viewAnimationsForCurrentUpdate]
7 | UIKit | __71-[UICollectionView _updateWithItems:tentativelyForReordering:animator:]_block_invoke.1983
8 | UIKit | +[UIView(Animation) performWithoutAnimation:]
9 | UIKit | -[UICollectionView _updateWithItems:tentativelyForReordering:animator:]
10 | UIKit | -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:]
11 | UIKit | -[UICollectionView _updateRowsAtIndexPaths:updateAction:]

**Comment by dev-liyang** [comment]
[iOS10崩溃了 #15](https://github.com/dev-liyang/LYEmptyView/issues/15)
[不知道为啥我的运行在iOS 10.3.2系统中tableView调用reloadData老是崩溃 #16](https://github.com/dev-liyang/LYEmptyView/issues/16)
