### ISSUE TITLE
崩溃到ly_reloadSections 是什么问题啊？

### ISSUE THREAD

**Issue by LJW008** [dev-liyang/LYEmptyView#34]
![image](https://user-images.githubusercontent.com/11679563/50586041-6ada5c00-0e3d-11e9-8f0a-9f3738ed2baf.png)

**Comment by dev-liyang** [comment]
经过method swizzling 后ly_reloadSections和系统的reloadSections方法的IMP已经交换，崩在这里其实是调用系统的reloadSections方法发生崩溃了。所以请检查你的参数设置有无问题

**Comment by LJW008** [comment]
> 经过method swizzling 后ly_reloadSections和系统的reloadSections方法的IMP已经交换，崩在这里其实是调用系统的reloadSections方法发生崩溃了。所以请检查你的参数设置有无问题

自己写了个demo，确实是如你所说，
