### ISSUE TITLE
新版本 1.2.3 崩溃 [UIimage imageNamed:]

### ISSUE THREAD

**Issue by leisong1125** [dev-liyang/LYEmptyView#36]
[framework] CUICatalog: Invalid asset name supplied: '(null)'
自定义的 视图 emptyView(withCustomView: )  image  应该可以为空的

**Comment by jiaoyaxin** [comment]
//占位图片
    UIImage *image = nil;
    if (self.imageStr.length) {
       image = [UIImage imageNamed:self.imageStr];
    }

请迫症在此

**Comment by dev-liyang** [comment]
已更新
