### ISSUE TITLE
为何使用customView时如果Autolayout布局会导致APP卡住

### ISSUE THREAD

**Issue by snailzzj** [dev-liyang/LYEmptyView#39]
`
let v = UIView()
let iv = UIView()
v.addSubview(iv)
 
// 只要CustomView添加了约束就会卡死主线程？
iv.snp.makeConstraints { (make) in
      make.edges.equalToSuperview()
}
        
let ev = LYEmptyView.emptyView(withCustomView: v)
tableView.ly_emptyView = ev
`

**Comment by jiaoyaxin** [comment]
1 iv约束不完整啊
2 给v加个预设size，intrinsicContentSize 试试？

**Comment by snailzzj** [comment]
并没有什么卵用

**Comment by snailzzj** [comment]
并没有什么卵用

**Comment by 77xiaozi** [comment]
同样遇到这个问题，无法使用Masonry进行布局。
UI会卡死 闪退

**Comment by jiaoyaxin** [comment]
作者用了
- (void)prepare{
    
    self.autoresizingMask = UIViewAutoresizingFlexibleWidth |  UIViewAutoresizingFlexibleHeight;
}

masonry用了
- (NSArray *)mas_makeConstraints:(void(^)(MASConstraintMaker *))block {
    self.translatesAutoresizingMaskIntoConstraints = NO;
    MASConstraintMaker *constraintMaker = [[MASConstraintMaker alloc] initWithView:self];
    block(constraintMaker);
    return [constraintMaker install];
}

额。。。你手写view frame给 lyempty custom就行，
 或者把作者的也改成Autolayout。

**Comment by dev-liyang** [comment]
本框架暂不支持Autolayout，使用Autolayout会导致死循环
