### ISSUE TITLE
搜不到啊

### ISSUE THREAD

**Issue by MR-THT** [dev-liyang/LYEmptyView#4]
我也搜不到
MR_THT$ pod --version
1.3.1
Mac:~ $ pod search LYEmptyView
[!] Unable to find a pod with name, author, summary, or description matching LYEmptyView

**Comment by yangli-dev** [comment]
提供几个参考的解决办法:
1.更新下本地仓库 $ pod repo update
2. 
   1) 执行命令重装 ，$ sudo gem install -n /usr/local/bin cocoapods   
   2) $ pod setup
3. 以上两种方式还不行，请参考 https://www.jianshu.com/p/9e4e36ba8574
