### ISSUE TITLE
可不可以增加单独设置标签和按钮的间距

### ISSUE THREAD

**Issue by deanli08** [dev-liyang/LYEmptyView#44]
只有统一设置subViewMargin 间距，比如我要设置标签和图片间距是10 ，标签和按钮的间距是50这样就没办法了

**Comment by Abnerzj** [comment]
我这里也有这个需求，所以我fork了项目，然后添加了几个属性配置，已经提交给作者了。增加的内容是：
1，添加标题与图片之间的间距属性
2，添加详细描述 与 (标题或图片) 之间的间距属性
3，添加按钮 与 (详细描述或标题或图片)之间的间距属性
4，按钮添加背景颜色渐变属性

**Comment by dev-liyang** [comment]
👍给力
