### ISSUE TITLE
一直不显示，希望可以改善一下

### ISSUE THREAD

**Issue by Abnerzj** [dev-liyang/LYEmptyView#46]
设置autoShowEmptyView为NO后，`[tableView ly_showEmptyView];`必须放在`[tableView reloadData];`后面处理，否则reloadData时会隐藏。

**Comment by NingMengYe** [comment]
是设置
[self.tableView ly_startLoading];
 [self.tableView ly_endLoading];吧

**Comment by Abnerzj** [comment]
这两个方法我没有调用

**Comment by dev-liyang** [comment]
1.3.1已完善
