### ISSUE TITLE
ly_startLoading  刷新tableView会闪动

### ISSUE THREAD

**Issue by NingMengYe** [dev-liyang/LYEmptyView#48]
设置   self.tableView.ly_emptyView.autoShowEmptyView = NO;

然后在tableView reloadData 之后设置[self.tableView ly_endLoading];

刷新的时候tableView闪动是怎么回事

**Comment by dev-liyang** [comment]
闪动是无法避免的，就像loading一样在异步请求回调时间很短的情况下都会有闪动的感觉
