### ISSUE TITLE
1.3.1版本bug

### ISSUE THREAD

**Issue by FantasticSkyBaby** [dev-liyang/LYEmptyView#50]
描述：
tableview空页面，不采用reloadData方式刷新数据源，而使用insertRowAtIndexPath插入一条，emptyView没有hidden。

场景：
采用wiki 6.延迟显示emptyView方式

问题验证：
修改insertRowAtIndexPath为reloadData可修复

代码：
[self.dataArray insertObject:obj atIndex:0];
    [self.tableView beginUpdates];
    NSIndexPath *indexPath = [NSIndexPath indexPathForRow: 0];
    [self.tableView insertRowAtIndexPath:indexPath withRowAnimation:UITableViewRowAnimationNone];
    [self.tableView endUpdates];

**Comment by dev-liyang** [comment]
要保证在tableView刷新后调用 [self.tableView ly_endLoading]

**Comment by FantasticSkyBaby** [comment]
跟我项目里逻辑有些冲突，我重置到1.3.0了
